services:
  postgres:
    image: postgres

    container_name: wp-labs

    environment:
      POSTGRES_DB: labdb
      POSTGRES_USER: wp
      POSTGRES_PASSWORD: wp123

    ports:
      - "9555:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

    restart: unless-stopped

